name: NerdLag
version: 0.2.0
author: totemo
description: Tools for detecting various kinds of lag.
website: http://github.com/totemo/NerdLag
main: io.totemo.nerdlag.NerdLag
permissions:
  nerdlag.admin:
    description: Permission to administer the plugin.
    default: op
commands:
  nerdlag:
    description: Main plugin command.
    permission: nerdlag.admin
    usage: |
      /<command> event watch <plugin> [<thresh_nanos>]: Start watching event durations for <plugin> (can be "all"), with optional instantaneous reporting above a threshold.
      /<command> event unwatch <plugin>: Stop watching event durations for <plugin> (can be "all").
      /<command> event notify (on|off): Control in-game notifications of reports of events taking longer than the threshold.
      /<command> event log (on|off): Control logging of reports of events taking longer than the threshold.

